### ISSUE TITLE
Issue in installing RQuantLib 0.4.3 for Windows

### ISSUE THREAD

**Issue by huihuibear** [ghrr/drat#3]
I got the following error messages in installing from the zip file:
Error in read.dcf(file.path(pkgname, "DESCRIPTION"), c("Package", "Type")) : 
  cannot open the connection
In addition: Warning messages:
1: In unzip(zipname, exdir = dest) : error 1 in extracting from zip file
2: In read.dcf(file.path(pkgname, "DESCRIPTION"), c("Package", "Type")) :
  cannot open compressed file 'RQuantLib/DESCRIPTION', probable reason 'No such file or directory'

**Comment by eddelbuettel** [comment]
Please keep the discussion over where you started it.
