### ISSUE TITLE
RQuantLib binary for Mac OSX

### ISSUE THREAD

**Issue by javacom** [ghrr/drat#4]
Hi,
I have compiled MacOSX binary for R 3.5.0 (RQuantLib_0.4.4_R350.tgz)
available here
https://drive.google.com/uc?id=1yxEyYPhkq-_860_W0KY2_uxY4udY7yfE&export=download

See if this can be uploaded to your repo

**Comment by eddelbuettel** [comment]
Yes, you kindly reported that already over at the other repo.

But ... I have no idea who you are, you post under a pseudonym, and I have no way to test this (as I have no macOS box). 

I do not think I can distribute code under such conditions.
