### ISSUE TITLE
RQuantLib fail to install in R 3.5.1

### ISSUE THREAD

**Issue by jguevara0629** [ghrr/drat#5]
Hello, I recently posted on [SO](https://stackoverflow.com/questions/51167419/installing-rquantlib-on-windows-r-version-3-5-1?noredirect=1#comment89319216_51167419) but think a new build is required for use?

**Comment by eddelbuettel** [comment]
Someone needs to builds a new binary for Windows under R 3.5.*.  

Mayne @jeroen or @joshuaulrich can help...

**Comment by jeroen** [comment]
I thought we fixed this already? @jguevara0629 can you try:

```r
remotes::install_github("eddelbuettel/rquantlib")
```

Or alternatively you can submit the source pkg to the win builder and download the binary pkg.

**Comment by eddelbuettel** [comment]
We may well have fixed it... and I may not have updated the drat repo with the final zip.

Are you sure winbuilder would get through this and not time out?  Did we ever try?  (Great idea though.)

**Comment by jguevara0629** [comment]
@jeroen I tried doing that already without any luck:

```
install_github("eddelbuettel/rquantlib")
Downloading GitHub repo eddelbuettel/rquantlib@master
Installing package into ‘C:/Users/frys/Documents/R/win-library/3.5’
(as ‘lib’ is unspecified)
* installing *source* package 'RQuantLib' ...

   **********************************************
   WARNING: this package has a configure script
         It probably needs manual configuration
   **********************************************


** libs

*** arch - i386
rm -f RQuantLib.dll RcppExports.o affine.o asian.o barrier_binary.o bermudan.o bonds.o calendars.o curves.o dates.o daycounter.o discount.o hullwhite.o implieds.o modules.o sabr.o schedule.o utils.o vanilla.o zero.o
"C:/PROGRA~1/R/R-35~1.1/bin/i386/Rscript.exe" "../tools/winlibs.R"
c:/Rtools/mingw_32/bin/g++  -I"C:/PROGRA~1/R/R-35~1.1/include" -DNDEBUG -I../windows/quantlib-1.12.1/include -I../inst/include -I"C:/Users/frys/Documents/R/win-library/3.5/Rcpp/include"     -fopenmp   -O2 -Wall  -mtune=generic -c RcppExports.cpp -o RcppExports.o
/bin/sh: c:/Rtools/mingw_32/bin/g++: No such file or directory
make: *** [C:/PROGRA~1/R/R-35~1.1/etc/i386/Makeconf:215: RcppExports.o] Error 127
ERROR: compilation failed for package 'RQuantLib'
* removing 'C:/Users/frys/Documents/R/win-library/3.5/RQuantLib'
In R CMD INSTALL
Warning messages:
1: In missing_devel_warning(pkgdir) :
  Package RQuantLib has compiled code, but no suitable compiler(s) were found. Installation will likely fail.
  Install Rtools and make sure it is in the PATH.
2: In i.p(...) :
  installation of package ‘C:/Users/frys/AppData/Local/Temp/Rtmpe635UH/remotes1c64638627b6/eddelbuettel-rquantlib-f3fd11c’ had non-zero exit status
```

**Comment by jeroen** [comment]
@jguevara0629 it looks like you don't have rtools installed, or at least not int he expected path.

**Comment by jguevara0629** [comment]
@jeroen I cannot install Rtools under R 3.5.1 lol

**Comment by eddelbuettel** [comment]
Why? Everybody else can. Per https://cran.r-project.org/bin/windows/Rtools/ it is `Rtools35.exe`

**Comment by jguevara0629** [comment]
@eddelbuettel @jeroen that seem to work. I have successfully installed RQuantLib. Thanks & very much appreciate your help

**Comment by eddelbuettel** [comment]
Woot!!  

So to recap, with
- the proper R version 3.5.*
- the corresponding Rtools version
- the CRAN _source_ package installs using the QuantLib library from @jeroen's rwinlib repo?

That was the plan. Nice to see it work :)

**Comment by jguevara0629** [comment]
yes I had an open Question on [SO](https://stackoverflow.com/questions/51167419/installing-rquantlib-on-windows-r-version-3-5-1?noredirect=1#comment89319216_51167419)

Here is the recap:

I had to first install Rtools Rtools35.exe. After the installation was completed, I then went into my R-console and typed the following:

```
#install remotes
install.packages('remotes');library('remotes')

# install RQuantLib: Installation took a few minutes
install_github("eddelbuettel/rquantlib")

# After I ran this, RQuantLib was ready to use
library('RQuantLib')
```

**Comment by chinsoon12** [comment]
further background in https://github.com/eddelbuettel/rquantlib/issues/56
and if QuantLib needs to be upgraded in rwinlib/quantlib, see this commit: https://github.com/eddelbuettel/rquantlib/commit/e42d071dc5418c858de3584d6cc6e41a5bd184e8
for further changes required
